export const getPackages = (locale: string) => [
    {
        id: 'starter',
        name: locale === 'en' ? 'Starter Package' : 'স্টার্টার প্যাকেজ',
        price: 500,
        sms: 1000,
        validity: 30,
        description: 'Perfect for small businesses and startups',
        includes: [
            'Basic API Access',
            'Email Support',
            'Standard Delivery',
            'Basic Reporting',
        ],
        costPerSMS: 0.5,
        dailyLimit: 100,
    },
    {
        id: 'business',
        name: locale === 'en' ? 'Business Package' : 'বিজনেস প্যাকেজ',
        price: 2000,
        sms: 5000,
        validity: 60,
        description: 'Ideal for growing businesses with higher volume needs',
        includes: [
            'Advanced API Access',
            'Priority Email Support',
            'Fast Delivery',
            'Custom Sender ID',
            'Detailed Analytics',
        ],
        costPerSMS: 0.4,
        dailyLimit: 250,
    },
    {
        id: 'enterprise',
        name: locale === 'en' ? 'Corporate Package' : 'কর্পোরেট প্যাকেজ',
        price: 8000,
        sms: 25000,
        validity: 90,
        description: 'Complete solution for large organizations',
        includes: [
            'Premium API Access',
            '24/7 Phone Support',
            'Instant Delivery',
            'Multiple Sender IDs',
            'Advanced Analytics Dashboard',
            'Dedicated Account Manager',
            'Custom Integration Support',
        ],
        costPerSMS: 0.32,
        dailyLimit: 833,
    },
    {
        id: 'premium',
        name: locale === 'en' ? 'Premium Package' : 'প্রিমিয়াম প্যাকেজ',
        price: 15000,
        sms: 50000,
        validity: 120,
        description: 'Ultimate package for maximum performance and features',
        includes: [
            'Ultimate API Access',
            'VIP Support Channel',
            'Priority Network Routing',
            'Unlimited Sender IDs',
            'Real-time Analytics & Reporting',
            'Personal Account Manager',
            'White-label API Solution',
            'SLA with 99.9% Uptime Guarantee',
        ],
        costPerSMS: 0.3,
        dailyLimit: 1250,
    },
];

export const getPackageById = (id: string, locale: string) => {
    return getPackages(locale).find((pkg) => pkg.id === id);
};
